
server:
  port: ${ CONTAINER_PORT:5050 }
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [request_id: %X{request_id}] %-5level %logger{36} - %msg%n"
  level:
    root: ${APP_LOG_LEVEL:INFO}
    com:
      fourkites:
        facilities:
          dy:
            eventdataingestion:
              controller: ${ CONTROLLER_LOG_LEVEL:DEBUG }
              service: ${ SERVICE_LOG_LEVEL:TRACE }
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
spring:
  datasource:
    url: ${ JDBC_URL:jdbc:postgresql://127.0.0.1:5431/yms_app_db }
    username: ${ JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD}
    hikari:
      maxPoolSize: ${HIKARI_POOL_SiZE:10}
      poolName: ${POOL_NAME:DY-pool}


